workflows:
  socialtask:
    name: SocialTask Android & iOS
    max_build_duration: 30
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      java: 17
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
      - name: Flutter Build iOS
        script: |
          flutter build ios --release --no-codesign
          cd /build/ios/iphoneos/
          unzip -o -qq Runner.app.zip
          mkdir Payload
          mv -f Runner.app Payload/
          zip -qr Payload.zip Payload/
          mv -f Payload.zip SocialTask.ipa
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.ipa
