name: Add APK to Existing Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'

    - name: Install Dependencies
      run: |
        flutter pub get

    - name: Build APK
      run: |
        flutter build apk --release

    - name: Get Last Commit ID
      id: last_commit
      run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"

    - name: Upload APK to Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        curl -X POST "https://api.github.com/repos/SocialTask/SocialTask/releases/${{ steps.last_commit.outputs.commit }}/assets?name=SocialTask.apk" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/vnd.android.package-archive" \
          --data-binary "@app/build/app/outputs/flutter-apk/app-release.apk"
